language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

services:
  - mysql

before_script:
  - mysql -e "create database engelsystem;" -uroot;  
  - mysql -e "use engelsystem;" -uroot;
  - mysql engelsystem -e "source ./db/install.sql;" -uroot;
  - mysql engelsystem -e "source ./db/update.sql;" -uroot;

script: cd test && phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
    code_climate:
        repo_token: f18d878e6000ffe79bf07df5fc8a7655185edb13a8103d05e0de9fa9d80941f0
